"""
app/schemas/analytics.py

Pydantic v2 schemas for the Analytics module.

These schemas define the read-only aggregations and reports generated by the AnalyticsService.

Milestone 2 additions:
  PredictionReportItem  — single prediction in the report
  PredictionReportRead  — response for GET /analytics/predictions
"""
from datetime import datetime
from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from app.models.alert import AlertSeverity
from app.models.prediction import PredictionStatus
from app.models.segment import CongestionLevel
from app.schemas.insight import TrafficInsightRead


# ── System Summary ────────────────────────────────────────────────────────────

class AnalyticsSummaryRead(BaseModel):
    """System-wide snapshot of active traffic conditions."""

    total_segments: int
    active_alerts: int
    critical_alerts: int
    congestion_distribution: dict[CongestionLevel, int]

    model_config = ConfigDict(from_attributes=True)


# ── Heatmap ───────────────────────────────────────────────────────────────────

class HeatmapItemRead(BaseModel):
    """Current congestion state for a single segment."""

    segment_id: UUID
    congestion_level: CongestionLevel
    vehicle_count: int
    average_speed_kmh: float
    recorded_at: datetime

    start_latitude: float
    start_longitude: float
    end_latitude: float
    end_longitude: float

    model_config = ConfigDict(from_attributes=True)


# ── Peak Hours ────────────────────────────────────────────────────────────────

class PeakHourRead(BaseModel):
    """Hourly average metrics for peak-hour analysis."""

    hour: datetime
    avg_vehicle_count: float
    avg_speed_kmh: float

    model_config = ConfigDict(from_attributes=True)


# ── Segment History ───────────────────────────────────────────────────────────

class HistoryBucketRead(BaseModel):
    """Time-bucketed aggregated readings for a segment."""

    bucket_start: datetime
    avg_vehicle_count: float
    avg_speed_kmh: float
    reading_count: int

    model_config = ConfigDict(from_attributes=True)


# ── Segment Trends ────────────────────────────────────────────────────────────

class TrendDirection(str, Enum):
    """Directional classification of a traffic trend."""
    INCREASING = "INCREASING"
    DECREASING = "DECREASING"
    STABLE = "STABLE"


class HourlyTrend(BaseModel):
    """Comparing an hour of the day across two periods."""

    hour_of_day: int = Field(..., ge=0, le=23)
    current_avg_vehicle_count: float
    prior_avg_vehicle_count: float
    delta_percent: float | None = Field(
        ...,
        description="Percentage change. None if prior period was 0.",
    )
    trend_direction: TrendDirection = Field(
        ...,
        description="Categorical classification of the trend based on configured thresholds.",
    )


class SegmentTrendsRead(BaseModel):
    """Statistical trends comparing the last 7 days to the prior 7 days."""

    segment_id: UUID
    hourly_trends: list[HourlyTrend]

    model_config = ConfigDict(from_attributes=True)


# ── Full Report ───────────────────────────────────────────────────────────────

class FullReportRead(BaseModel):
    """Comprehensive analytics report over a specified date range."""

    report_from: datetime
    report_to: datetime
    active_segment_count: int
    active_alerts_by_severity: dict[AlertSeverity, int]
    congestion_distribution: dict[CongestionLevel, int]
    prediction_completion_rate: float = Field(
        ...,
        description="Ratio of COMPLETED predictions to total predictions (0.0 to 1.0)",
    )
    busiest_hour: datetime | None

    model_config = ConfigDict(from_attributes=True)


# ── Prediction Report (Milestone 2) ──────────────────────────────────────────

class PredictionReportItem(BaseModel):
    """Single prediction entry in the prediction performance report."""

    id: UUID
    segment_id: UUID
    status: PredictionStatus
    model_version: str | None
    prediction_for: datetime
    horizon_minutes: int
    predicted_congestion_level: CongestionLevel | None
    predicted_vehicle_count: int | None
    predicted_avg_speed_kmh: float | None
    confidence_score: float | None
    requested_at: datetime
    completed_at: datetime | None

    model_config = ConfigDict(from_attributes=True)


class PredictionReportRead(BaseModel):
    """
    Prediction performance report response for GET /analytics/predictions.

    Provides real prediction data; no fabricated accuracy metrics.
    """

    total_predictions: int
    completed: int
    failed: int
    pending: int
    completion_rate: float = Field(
        ...,
        description="Fraction of predictions in COMPLETED status (0.0-1.0).",
    )
    predictions: list[PredictionReportItem]


# ── AI Traffic Report (Milestone 3 Stage 6) ───────────────────────────────────

class AITrafficReportRead(BaseModel):
    """
    Comprehensive system-level AI traffic report.
    Aggregates traffic, alerts, predictions, trends, and bounded insights.
    """
    generated_at: datetime
    report_from: datetime
    report_to: datetime
    
    active_segment_count: int
    congestion_distribution: dict[CongestionLevel, int]
    active_alerts_by_severity: dict[AlertSeverity, int]
    
    total_predictions: int
    prediction_completion_rate: float
    
    trend_distribution: dict[TrendDirection, int]
    
    insights: list[TrafficInsightRead]

    model_config = ConfigDict(from_attributes=True)

