"""
app/schemas/analytics.py

Pydantic v2 schemas for the Analytics module.

These schemas define the read-only aggregations and reports generated by the AnalyticsService.
"""
from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from app.models.alert import AlertSeverity
from app.models.segment import CongestionLevel


# ── System Summary ────────────────────────────────────────────────────────────

class AnalyticsSummaryRead(BaseModel):
    """System-wide snapshot of active traffic conditions."""

    total_segments: int
    active_alerts: int
    critical_alerts: int
    congestion_distribution: dict[CongestionLevel, int]

    model_config = ConfigDict(from_attributes=True)


# ── Heatmap ───────────────────────────────────────────────────────────────────

class HeatmapItemRead(BaseModel):
    """Current congestion state for a single segment."""

    segment_id: UUID
    congestion_level: CongestionLevel
    vehicle_count: int
    average_speed_kmh: float
    recorded_at: datetime

    model_config = ConfigDict(from_attributes=True)


# ── Peak Hours ────────────────────────────────────────────────────────────────

class PeakHourRead(BaseModel):
    """Hourly average metrics for peak-hour analysis."""

    hour: datetime
    avg_vehicle_count: float
    avg_speed_kmh: float

    model_config = ConfigDict(from_attributes=True)


# ── Segment History ───────────────────────────────────────────────────────────

class HistoryBucketRead(BaseModel):
    """Time-bucketed aggregated readings for a segment."""

    bucket_start: datetime
    avg_vehicle_count: float
    avg_speed_kmh: float
    reading_count: int

    model_config = ConfigDict(from_attributes=True)


# ── Segment Trends ────────────────────────────────────────────────────────────

class HourlyTrend(BaseModel):
    """Comparing an hour of the day across two periods."""

    hour_of_day: int = Field(..., ge=0, le=23)
    current_avg_vehicle_count: float
    prior_avg_vehicle_count: float
    delta_percent: float | None = Field(
        ...,
        description="Percentage change. None if prior period was 0.",
    )


class SegmentTrendsRead(BaseModel):
    """Statistical trends comparing the last 7 days to the prior 7 days."""

    segment_id: UUID
    hourly_trends: list[HourlyTrend]

    model_config = ConfigDict(from_attributes=True)


# ── Full Report ───────────────────────────────────────────────────────────────

class FullReportRead(BaseModel):
    """Comprehensive analytics report over a specified date range."""

    report_from: datetime
    report_to: datetime
    active_segment_count: int
    active_alerts_by_severity: dict[AlertSeverity, int]
    congestion_distribution: dict[CongestionLevel, int]
    prediction_completion_rate: float = Field(
        ...,
        description="Ratio of COMPLETED predictions to total predictions (0.0 to 1.0)",
    )
    busiest_hour: datetime | None

    model_config = ConfigDict(from_attributes=True)
